export interface AnatomicalPart {
  id: string;
  name: string;
  description: string;
}

export interface OrganSystemDefinition {
  id: string;
  name: string;
  description: string;
  color: number;
  emissive: number;
  parts: AnatomicalPart[];
}

function part(
  id: string,
  name: string,
  description = "",
): AnatomicalPart {
  return { id, name, description: description || `${name} — estructura anatómica.` };
}

export const ORGAN_SYSTEM_DEFINITIONS: OrganSystemDefinition[] = [
  {
    id: "ear",
    name: "Oído",
    description: "Oído externo, medio e interno con huesecillos y laberinto.",
    color: 0xe8b4a0,
    emissive: 0x4a3020,
    parts: [
      part("auditory_ring", "Auditory ring"),
      part("concha", "Concha"),
      part("auricle", "Auricle"),
      part("antihelix", "Antihelix"),
      part("helix", "Helix"),
      part("cartilage", "Cartilage"),
      part("auditory_canal", "Auditory canal"),
      part("tympanic_membrane", "Tympanic membrane"),
      part("tympanic_cavity", "Tympanic cavity"),
      part("eustachian_tube", "Eustachian tube"),
      part("temporal_bone", "Temporal bone"),
      part("muscle", "Muscle"),
      part("malleus", "Malleus"),
      part("incus", "Incus"),
      part("stapes", "Stapes"),
      part("semicircular_canals", "Semicircular canals"),
      part("cochlea", "Cochlea"),
      part("vestibular_nerve", "Vestibular nerve"),
    ],
  },
  {
    id: "brain",
    name: "Cerebro",
    description: "Estructuras del encéfalo y sistema límbico.",
    color: 0xf4a6a6,
    emissive: 0x5c2020,
    parts: [
      part("fornix", "Fornix"),
      part("cingulate_cortex", "Cingulate cortex"),
      part("corpus_callosum", "Corpus callosum"),
      part("thalamus", "Thalamus"),
      part("stria_terminalis", "Stria terminalis"),
      part("hippocampus", "Hippocampus"),
      part("amygdala", "Amygdala"),
      part("mammillary_bodies", "Mammillary bodies"),
      part("olfactory_bulb", "Olfactory bulb"),
      part("septum", "Septum"),
      part("frontal_cortex", "Frontal cortex"),
    ],
  },
  {
    id: "eyes",
    name: "Ojos",
    description: "Globo ocular y estructuras de la vía visual.",
    color: 0xa8d8ea,
    emissive: 0x1a3d4d,
    parts: [
      part("iris", "Iris"),
      part("ciliary_body", "Ciliary body"),
      part("blood_vessels", "Blood vessels"),
      part("macula", "Macula"),
      part("optic_nerve", "Optic nerve"),
      part("retina", "Retina"),
      part("choroid", "Choroid"),
      part("sclera", "Sclera"),
      part("conjunctiva", "Conjunctiva"),
      part("cornea", "Cornea"),
      part("pupil", "Pupil"),
      part("aqueous_humor", "Aqueous humor"),
    ],
  },
  {
    id: "nose",
    name: "Nariz",
    description: "Cavidad nasal, senos paranasales y fosas.",
    color: 0xd4b5ff,
    emissive: 0x3d2a5c,
    parts: [
      part("septum", "Septum"),
      part("frontal_sinus", "Frontal sinus"),
      part("ethmoid_sinus", "Ethmoid sinus"),
      part("maxillary_sinus", "Maxillary sinus"),
      part("nasal_fossa", "Nasal fossa"),
      part("nostrils", "Nostrils"),
      part("external_nose", "External Nose"),
    ],
  },
  {
    id: "neck",
    name: "Cuello",
    description: "Músculos y estructuras del cuello.",
    color: 0xc9a66b,
    emissive: 0x3d3018,
    parts: [
      part("sternohyoid", "Sternohyoid"),
      part("semispinalis_cervicis", "Semispinalis Cervicis"),
      part("splenius_capitis", "Splenius Capitis"),
      part("levator_scapulae", "Levator Scapulae"),
      part("scalenes", "Scalenes"),
      part("trapezius", "Trapezius"),
      part("omohyoid", "Omohyoid"),
      part("sternocleidomastoid", "Sternocleidomastoid"),
    ],
  },
  {
    id: "lung",
    name: "Pulmón",
    description: "Vías aéreas y lóbulos pulmonares.",
    color: 0xff9eb5,
    emissive: 0x5c1f30,
    parts: [
      part("carina", "Carina"),
      part("trachea", "Trachea"),
      part("superior_lobe_right", "Superior Lobe (right)"),
      part("oblique_fissure", "Oblique Fissure"),
      part("inferior_lobe", "Inferior Lobe"),
      part("middle_lobe", "Middle Lobe"),
      part("horizontal_fissure", "Horizontal Fissure"),
      part("superior_lobe_left", "Superior Lobe (left)"),
    ],
  },
  {
    id: "digestive",
    name: "Sistema digestivo",
    description: "Tracto gastrointestinal principal.",
    color: 0xf4a261,
    emissive: 0x5c3a12,
    parts: [
      part("liver", "Liver"),
      part("esophagus", "Esophagus"),
      part("stomach", "Stomach"),
      part("colon", "Colon"),
      part("appendix", "Appendix"),
      part("cecum", "Cecum"),
      part("small_intestine", "Small Intestine"),
      part("duodenum", "Duodenum"),
    ],
  },
  {
    id: "heart",
    name: "Corazón",
    description: "Cavidades, válvulas y grandes vasos.",
    color: 0xe63946,
    emissive: 0x6b1018,
    parts: [
      part("superior_vena_cava", "Superior Vena Cava"),
      part("aorta", "Aorta"),
      part("pulmonary_artery", "Pulmonary Artery"),
      part("pulmonary_veins", "Pulmonary Veins"),
      part("left_atrium", "Left Atrium"),
      part("mitral_valve", "Mitral Valve"),
      part("aortic_valve", "Aortic Valve"),
      part("left_ventricle", "Left Ventricle"),
      part("pericardium", "Pericardium"),
      part("right_ventricle", "Right Ventricle"),
      part("pulmonary_valve", "Pulmonary Valve"),
      part("tricuspid_valve", "Tricuspid Valve"),
      part("pulmonary_trunk", "Pulmonary Trunk"),
      part("right_atrium", "Right Atrium"),
    ],
  },
  {
    id: "thyroid",
    name: "Tiroides",
    description: "Laringe, tráquea y glándula tiroides.",
    color: 0xc77dff,
    emissive: 0x4a1f6e,
    parts: [
      part("larynx", "Larynx"),
      part("gland", "Gland"),
      part("thyroid_gland", "Thyroid Gland"),
      part("trachea", "Trachea"),
    ],
  },
  {
    id: "stomach",
    name: "Estómago",
    description: "Regiones del estómago.",
    color: 0xffb347,
    emissive: 0x5c4010,
    parts: [
      part("fundus", "Fundus"),
      part("body", "Body"),
      part("antrum", "Antrum"),
      part("pyloric_canal", "Pyloric canal"),
      part("cardia", "Cardia"),
    ],
  },
  {
    id: "male_reproductive",
    name: "Aparato reproductor masculino",
    description: "Órganos reproductivos y vías urinarias masculinas.",
    color: 0x7b9acc,
    emissive: 0x1a2d4d,
    parts: [
      part("ureter", "Ureter"),
      part("seminal_vesicle", "Seminal vesicle"),
      part("ejaculatory_duct", "Ejaculatory duct"),
      part("rectum", "Rectum"),
      part("testicle", "Testicle"),
      part("urethra", "Urethra"),
      part("penis", "Penis"),
      part("vas_deferens", "Vas deferens"),
      part("prostate_gland", "Prostate gland"),
      part("bladder", "Bladder"),
    ],
  },
  {
    id: "female_reproductive",
    name: "Aparato reproductor femenino",
    description: "Útero, ovarios y vías genitales.",
    color: 0xf72585,
    emissive: 0x5c0a30,
    parts: [
      part("fallopian_tube", "Fallopian tube"),
      part("ovary", "Ovary"),
      part("uterus", "Uterus"),
      part("cervix", "Cervix"),
      part("vagina", "Vagina"),
      part("myometrium", "Myometrium"),
      part("endometrium", "Endometrium"),
    ],
  },
  {
    id: "bladder",
    name: "Vejiga",
    description: "Vejiga urinaria y estructuras asociadas.",
    color: 0xf9c74f,
    emissive: 0x4a3d08,
    parts: [
      part("ureter", "Ureter"),
      part("mucosa", "Mucosa"),
      part("urethral_openings", "Urethral openings"),
      part("fat_layer", "Fat layer"),
      part("trigone", "Trigone of the bladder"),
      part("neck", "Neck"),
      part("muscular_layers", "Muscular layers"),
      part("urethra", "Urethra"),
    ],
  },
  {
    id: "pancreas",
    name: "Páncreas",
    description: "Páncreas y conductos biliopancreáticos.",
    color: 0xffd166,
    emissive: 0x5c4a12,
    parts: [
      part("pancreatic_duct", "Pancreatic duct"),
      part("tail", "Tail"),
      part("body", "Body"),
      part("head", "Head of the pancreas"),
      part("small_intestine", "Small intestine"),
      part("duodenum", "Duodenum"),
      part("common_bile_duct", "Common bile duct"),
    ],
  },
  {
    id: "kidneys",
    name: "Riñones",
    description: "Filtración renal y vías de salida.",
    color: 0x6b4226,
    emissive: 0x2a1508,
    parts: [
      part("unfiltered_blood", "Unfiltered blood"),
      part("filtered_blood", "Filtered blood"),
      part("ureter", "Ureter"),
      part("urine_to_bladder", "Urine flows to the bladder"),
    ],
  },
  {
    id: "liver",
    name: "Hígado",
    description: "Lóbulos hepáticos y vías biliares.",
    color: 0x8b4513,
    emissive: 0x3d1f0a,
    parts: [
      part("left_lobe", "Left lobe"),
      part("esophagus", "Esophagus"),
      part("stomach", "Stomach"),
      part("pancreas", "Pancreas"),
      part("duodenum", "Duodenum"),
      part("gallbladder", "Gallbladder"),
      part("common_hepatic_duct", "Common hepatic duct"),
      part("right_lobe", "Right lobe"),
    ],
  },
];

export const ORGAN_SYSTEM_BY_ID = Object.fromEntries(
  ORGAN_SYSTEM_DEFINITIONS.map((s) => [s.id, s]),
) as Record<string, OrganSystemDefinition>;
